name: docker
on:
  push:
    branches:
      - main
    tags:
      - v*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate tag name
        id: calculate_tag
        run: |
          if echo $GITHUB_REF | grep -q '^refs/tags/v'; then
            VERSION=$(echo $GITHUB_REF | cut -d/ -f3);
            TAG_NAME="${{ secrets.DOCKER_HUB_PREFIX }}/mojopaste:$VERSION";
          else
            TAG_NAME="${{ secrets.DOCKER_HUB_PREFIX }}/mojopaste:latest";
          fi
          echo '::set-output name=tag::'$TAG_NAME
      - name: Check Out Repo
        uses: actions/checkout@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: "${{ steps.calculate_tag.outputs.tag }}"
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
