name: linux
on:
  pull_request:
  push:
    branches:
    - '**'
jobs:
  nodejs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
        - '5.26'
        - '5.34'
    container:
      image: perl:${{matrix.perl-version}}
    steps:
    - uses: actions/checkout@v2
    - name: perl -V
      run: perl -V
    - name: Install dependencies
      run: |
        cpanm -n Test::Pod Test::Pod::Coverage
        cpanm -n --installdeps .
    - name: Run perl tests
      run: prove -l
      env:
        HARNESS_OPTIONS: j4
        TEST_POD: 1
